"""Added Roof Image URLs

Revision ID: faa377114257
Revises: 
Create Date: 2025-03-16 16:14:21.755147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa377114257'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roof_square_feet', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('roof_image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_column('roof_image_url')
        batch_op.drop_column('roof_square_feet')

    # ### end Alembic commands ###
